repository:
  name: Emaily
  description: Emaily application
  homepage: https://github.com/pranay414/Emaily
  topics: javascript, node, react, mongodb
  has_wiki: false

labels:
  - name: "low hanging fruit"
    color: CC0000
