repository:
  name: Emaily
  description: Emaily application to send out surveys
  homepage: https://github.com/pranay414/Emaily
  topics: javascript, node, react, mongodb
  has_wiki: false

labels:
  - name: low hanging fruit
    color: CE93D8
