repository:
  name: Emaily
  description: Emaily app
  homepage: https://github.com/pranay414/Emaily
  topics: javascript
  has_wiki: false

labels:
  - name: "low hanging fruit :strawberry:"
    color: CC0000
